### PR TITLE
allow passthrough of legacy boyar configuration

### PR DESCRIPTION
**Pull request by amir-arad**

### CODE REVIEW

**Comment by netoneko** [comment]
Constantly crashes after reprovisioning with this error:

```
configuration value {"pollIntervalSeconds":1,"node-address":"a328846cd5b4979d68a8c58a9bdfeee657b34de7"}
```

**Comment by amir-arad** [comment]
> Constantly crashes after reprovisioning with this error:
> 
> ```
> illegal configuration value {"pollIntervalSeconds":1,"node-address":"a328846cd5b4979d68a8c58a9bdfeee657b34de7"}
> ```

did you supply a `boyarLegacyBootstrap`  parameter?

**Comment by netoneko** [comment]
All good

**Comment by netoneko** [comment]
First integration milestone passed: https://github.com/orbs-network/boyarin/pull/136

**Pull request merged**
